-- Generated by tools/build_gesture_maps.py - the ten shipped Gesture-Maps.
-- Apply with:  wrangler d1 execute kinesis-gesture-maps --remote --file=seed.sql

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'browser-power-user-0000-0000-0000-00', 'browser-power-user', 'Browser Power User', 'Tabs, pages and search without leaving the page you are reading. Peace sign is a new tab, three fingers closes one.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Browser Power User", "author": "Kinesis", "description": "Tabs, pages and search without leaving the page you are reading. Peace sign is a new tab, three fingers closes one.", "created": "2026-10-01", "bindings": [{"id": "new-tab", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["t"], "modifiers": ["ctrl"]}}, {"id": "close-tab", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["w"], "modifiers": ["ctrl"]}}, {"id": "reopen-tab", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["t"], "modifiers": ["ctrl", "shift"]}}, {"id": "next-tab", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["ctrl"]}}, {"id": "prev-tab", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["ctrl", "shift"]}}, {"id": "address-bar", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["l"], "modifiers": ["ctrl"]}}, {"id": "new-window", "enabled": true, "gesture": {"left": "open", "right": "peace"}, "action": {"type": "keys", "keys": ["n"], "modifiers": ["ctrl", "shift"]}}, {"id": "reopen-last", "enabled": true, "gesture": {"left": "fist", "right": "point"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["ctrl", "shift"]}}]}', 8, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'media-player-0000-0000-0000-00000000', 'media-player', 'Media Player', 'Play, seek, volume and mute for YouTube, Spotify or VLC. Works anywhere a space bar does.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Media Player", "author": "Kinesis", "description": "Play, seek, volume and mute for YouTube, Spotify or VLC. Works anywhere a space bar does.", "created": "2026-10-01", "bindings": [{"id": "play-pause", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["space"]}}, {"id": "seek-forward", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["right"]}}, {"id": "seek-back", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["left"]}}, {"id": "volume-up", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["up"]}}, {"id": "volume-down", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["down"]}}, {"id": "mute", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["m"]}}, {"id": "fullscreen", "enabled": true, "gesture": {"left": "fist", "right": "peace"}, "action": {"type": "keys", "keys": ["f"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'windows-navigation-0000-0000-0000-00', 'windows-navigation', 'Windows Navigation', 'Snap windows, task view and show desktop. Three fingers for task view, pinch your little finger to drop back to the desktop.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Windows Navigation", "author": "Kinesis", "description": "Snap windows, task view and show desktop. Three fingers for task view, pinch your little finger to drop back to the desktop.", "created": "2026-10-01", "bindings": [{"id": "task-view", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["win"]}}, {"id": "show-desktop", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["d"], "modifiers": ["win"]}}, {"id": "snap-left", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["left"], "modifiers": ["win"]}}, {"id": "snap-right", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["right"], "modifiers": ["win"]}}, {"id": "maximise", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["up"], "modifiers": ["win"]}}, {"id": "restore", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["down"], "modifiers": ["win"]}}, {"id": "alt-tab", "enabled": true, "gesture": {"left": "open", "right": "fist"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["alt"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'video-editing-0000-0000-0000-0000000', 'video-editing', 'Video Editing', 'Scrub, cut and undo on the timeline. Peace plays, three fingers cuts.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Video Editing", "author": "Kinesis", "description": "Scrub, cut and undo on the timeline. Peace plays, three fingers cuts.", "created": "2026-10-01", "bindings": [{"id": "play", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["space"]}}, {"id": "step-back", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["left"]}}, {"id": "step-fwd", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["right"]}}, {"id": "cut", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["k"], "modifiers": ["ctrl"]}}, {"id": "undo", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["z"], "modifiers": ["ctrl"]}}, {"id": "marker", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["m"]}}, {"id": "redo", "enabled": true, "gesture": {"left": "fist", "right": "three"}, "action": {"type": "keys", "keys": ["z"], "modifiers": ["ctrl", "shift"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'presentation-remote-0000-0000-0000-0', 'presentation-remote', 'Presentation Remote', 'Drive a slide deck from across the room. Peace advances, a point goes back, pinch your little finger to black the screen.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Presentation Remote", "author": "Kinesis", "description": "Drive a slide deck from across the room. Peace advances, a point goes back, pinch your little finger to black the screen.", "created": "2026-10-01", "bindings": [{"id": "next-slide", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["right"]}}, {"id": "prev-slide", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["left"]}}, {"id": "start-show", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["f5"]}}, {"id": "black-screen", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["b"]}}, {"id": "end-show", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["esc"]}}, {"id": "toggle-black", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["b"]}}]}', 6, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'coding---ide-0000-0000-0000-00000000', 'coding---ide', 'Coding / IDE', 'Command palette, go-to-file, find references and the terminal. Built for VS Code, works in any JetBrains editor with the same habits.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Coding / IDE", "author": "Kinesis", "description": "Command palette, go-to-file, find references and the terminal. Built for VS Code, works in any JetBrains editor with the same habits.", "created": "2026-10-01", "bindings": [{"id": "command-palette", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["p"], "modifiers": ["ctrl", "shift"]}}, {"id": "go-to-file", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["p"], "modifiers": ["ctrl"]}}, {"id": "find-references", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["f12"], "modifiers": ["shift"]}}, {"id": "comment-line", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["/"], "modifiers": ["ctrl"]}}, {"id": "terminal", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["`"], "modifiers": ["ctrl"]}}, {"id": "git-panel", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["g"], "modifiers": ["ctrl", "shift"]}}, {"id": "search-all", "enabled": true, "gesture": {"left": "fist", "right": "peace"}, "action": {"type": "keys", "keys": ["f"], "modifiers": ["ctrl", "shift"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'one-handed-essentials-0000-0000-0000', 'one-handed-essentials', 'One-Handed Essentials', 'The whole set on your right hand only, for when the other hand is busy, holding something, or out of action.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "One-Handed Essentials", "author": "Kinesis", "description": "The whole set on your right hand only, for when the other hand is busy, holding something, or out of action.", "created": "2026-10-01", "bindings": [{"id": "confirm", "enabled": true, "gesture": {"pose": "point", "hand": "right"}, "action": {"type": "keys", "keys": ["enter"]}}, {"id": "next-field", "enabled": true, "gesture": {"pose": "peace", "hand": "right"}, "action": {"type": "keys", "keys": ["tab"]}}, {"id": "cancel", "enabled": true, "gesture": {"pose": "three", "hand": "right"}, "action": {"type": "keys", "keys": ["esc"]}}, {"id": "switch-app", "enabled": true, "gesture": {"pose": "four", "hand": "right"}, "action": {"type": "keys", "keys": ["tab"], "modifiers": ["alt"]}}, {"id": "undo", "enabled": true, "gesture": {"pose": "pinky", "hand": "right"}, "action": {"type": "keys", "keys": ["z"], "modifiers": ["ctrl"]}}, {"id": "reopen", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "right"}, "action": {"type": "keys", "keys": ["t"], "modifiers": ["ctrl", "shift"]}}]}', 6, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'meeting-controls-0000-0000-0000-0000', 'meeting-controls', 'Meeting Controls', 'Mute, camera, raise hand and hang up, matching the Teams and Zoom shortcuts.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Meeting Controls", "author": "Kinesis", "description": "Mute, camera, raise hand and hang up, matching the Teams and Zoom shortcuts.", "created": "2026-10-01", "bindings": [{"id": "mute", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["m"], "modifiers": ["ctrl", "shift"]}}, {"id": "camera", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["v"], "modifiers": ["ctrl", "shift"]}}, {"id": "raise-hand", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["u"], "modifiers": ["ctrl", "shift"]}}, {"id": "hang-up", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["h"], "modifiers": ["ctrl", "shift"]}}, {"id": "share-screen", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["e"], "modifiers": ["ctrl", "shift"]}}]}', 5, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'reading-comfort-0000-0000-0000-00000', 'reading-comfort', 'Reading Comfort', 'Page through and resize long articles without touching the keyboard. Three fingers zooms in, four zooms out.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Reading Comfort", "author": "Kinesis", "description": "Page through and resize long articles without touching the keyboard. Three fingers zooms in, four zooms out.", "created": "2026-10-01", "bindings": [{"id": "page-down", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["pagedown"]}}, {"id": "page-up", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["pageup"]}}, {"id": "zoom-in", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["+"], "modifiers": ["ctrl"]}}, {"id": "zoom-out", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["-"], "modifiers": ["ctrl"]}}, {"id": "zoom-reset", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["0"], "modifiers": ["ctrl"]}}, {"id": "bookmark", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["d"], "modifiers": ["ctrl"]}}, {"id": "top-of-page", "enabled": true, "gesture": {"left": "fist", "right": "four"}, "action": {"type": "keys", "keys": ["home"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);

INSERT OR IGNORE INTO gesture_maps
  (id, slug, title, description, author_name, github_url, map_json, binding_count,
   downloads, featured, created_at)
VALUES (
  'gaming-hotbar-0000-0000-0000-0000000', 'gaming-hotbar', 'Gaming Hotbar', 'Slots one to five on your fingers, map and inventory on the extra gestures. Keyboard-only games; anything with an anti-cheat will ignore injected input.',
  'Kinesis', 'https://github.com/DrGekoz/Kinesis',
  '{"schema": "kinesis.gesture-map", "version": 1, "name": "Gaming Hotbar", "author": "Kinesis", "description": "Slots one to five on your fingers, map and inventory on the extra gestures. Keyboard-only games; anything with an anti-cheat will ignore injected input.", "created": "2026-10-01", "bindings": [{"id": "slot-1", "enabled": true, "gesture": {"pose": "peace", "hand": "either"}, "action": {"type": "keys", "keys": ["1"]}}, {"id": "slot-2", "enabled": true, "gesture": {"pose": "three", "hand": "either"}, "action": {"type": "keys", "keys": ["2"]}}, {"id": "slot-3", "enabled": true, "gesture": {"pose": "four", "hand": "either"}, "action": {"type": "keys", "keys": ["3"]}}, {"id": "slot-4", "enabled": true, "gesture": {"pose": "pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["4"]}}, {"id": "slot-5", "enabled": true, "gesture": {"pose": "point", "hand": "either"}, "action": {"type": "keys", "keys": ["5"]}}, {"id": "map", "enabled": true, "gesture": {"pose": "pinch_pinky", "hand": "either"}, "action": {"type": "keys", "keys": ["tab"]}}, {"id": "inventory", "enabled": true, "gesture": {"left": "fist", "right": "pinky"}, "action": {"type": "keys", "keys": ["m"]}}]}', 7, 0, 1, '2026-10-01T00:00:00Z'
);
